version = 0.1

[dev.deploy.parameters]
stack_name = "WS-Service-SKR"
resolve_s3 = true
s3_prefix = "WS-Service-SKR"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[dev.sync.parameters]
stack_name = "WS-Service-SKR"
resolve_s3 = true
s3_prefix = "WS-Service-SKR"
region = "ap-south-1"
confirm_changeset = false
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
image_repositories = []

[dev.global.parameters]
region = "ap-south-1"
