AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Web socket service

Globals:
  Function:
    Environment:
      Variables:
        AWS_REGION_OP: !Ref "AWS::Region"
    Runtime: nodejs24.x
    EphemeralStorage:
      Size: 1024
    CodeUri: .
    Timeout: 30

Resources:
  ConnectionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: WS-Connections-SKR
      PrimaryKey:
        Name: connectionId
        Type: String

  GroupTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WS-groups-SKR
      AttributeDefinitions:
        - AttributeName: groupId
          AttributeType: S
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: groupId
          KeyType: HASH
        - AttributeName: connectionId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  ConnectLambdaHandler:
    Type: AWS::Serverless::Function
    DependsOn: ConnectLambdaHandlerLogGroup
    Properties:
      FunctionName: ConnectHandler-WS-SKR
      Handler: connectHandler.handler
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - DynamoDBWritePolicy:
            TableName: !Ref ConnectionTable
        - DynamoDBWritePolicy:
            TableName: !Ref GroupTable
      Environment:
        Variables:
          CONNECTION_TABLE_NAME: !Ref ConnectionTable
          GROUP_TABLE_NAME: !Ref GroupTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/functions/connectHandler.ts
        External:
          - "@aws-sdk/client-dynamodb"
          - "aws-lambda"

  ConnectLambdaHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ConnectHandler-WS-SKR
      RetentionInDays: 7
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  DisconnectLambdaHandler:
    Type: AWS::Serverless::Function
    DependsOn: DisconnectLambdaHandlerLogGroup
    Properties:
      FunctionName: DisconnectHandler-WS-SKR
      Handler: disconnectHandler.handler
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupTable
      Environment:
        Variables:
          CONNECTION_TABLE_NAME: !Ref ConnectionTable
          GROUP_TABLE_NAME: !Ref GroupTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/functions/disconnectHandler.ts
        External:
          - "@aws-sdk/client-dynamodb"
          - "aws-lambda"

  DisconnectLambdaHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/DisconnectHandler-WS-SKR
      RetentionInDays: 7
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  SendMessageLambdaHandler:
    Type: AWS::Serverless::Function
    DependsOn: SendMessageLambdaHandlerLogGroup
    Properties:
      FunctionName: SendmessageHandler-WS-SKR
      Handler: sendMessage.handler
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - DynamoDBReadPolicy:
            TableName: !Ref ConnectionTable
        - DynamoDBReadPolicy:
            TableName: !Ref GroupTable
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketApi}/*"
      Environment:
        Variables:
          CONNECTION_TABLE_NAME: !Ref ConnectionTable
          GROUP_TABLE_NAME: !Ref GroupTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/functions/sendMessage.ts
        External:
          - "@aws-sdk/client-dynamodb"
          - "aws-lambda"
          - "@aws-sdk/client-apigatewaymanagementapi"

  SendMessageLambdaHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/SendmessageHandler-WS-SKR
      RetentionInDays: 7
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  DefaultLambdaHandler:
    Type: AWS::Serverless::Function
    DependsOn: DefaultLambdaHandlerLogGroup
    Properties:
      FunctionName: DefaultHandler-WS-SKR
      Handler: defaultHandler.handler
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketApi}/*"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/functions/defaultHandler.ts
        External:
          - "@aws-sdk/client-dynamodb"
          - "aws-lambda"
          - "@aws-sdk/client-apigatewaymanagementapi"

  DefaultLambdaHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/DefaultHandler-WS-SKR
      RetentionInDays: 7
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  WebsocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Websocket-Api-SKR
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  
  WebSocketLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/websocket/${WebsocketApi}"
      RetentionInDays: 7
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub integrations/${ConnectIntegration}
      
  ConnectGroupRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketApi
      RouteKey: connectGroup
      AuthorizationType: NONE
      Target: !Sub integrations/${ConnectIntegration}

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebsocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectLambdaHandler.Arn}/invocations"

  ConnectLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ConnectLambdaHandler.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketApi}/*"

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub integrations/${DisconnectIntegration}

  DisconnectGroupRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketApi
      RouteKey: disconnectGroup
      AuthorizationType: NONE
      Target: !Sub integrations/${DisconnectIntegration}

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebsocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DisconnectLambdaHandler.Arn}/invocations"

  DisconnectLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt DisconnectLambdaHandler.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketApi}/*"

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketApi
      RouteKey: $default
      AuthorizationType: NONE
      Target: !Sub integrations/${DefaultIntegration}

  DefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebsocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DefaultLambdaHandler.Arn}/invocations"

  DefaultLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt DefaultLambdaHandler.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketApi}/*"

  SendMessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketApi
      RouteKey: sendMessage
      AuthorizationType: NONE
      Target: !Sub integrations/${SendMessageIntegration}

  SendGroupMessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebsocketApi
      RouteKey: sendMessageGroup
      AuthorizationType: NONE
      Target: !Sub integrations/${SendMessageIntegration}

  SendMessageIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebsocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendMessageLambdaHandler.Arn}/invocations"

  SendMessageLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SendMessageLambdaHandler.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketApi}/*"

  ApiGatewayDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref WebsocketApi
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - DefaultRoute
      - SendMessageRoute
      - ConnectGroupRoute
      - DisconnectGroupRoute
      - SendGroupMessageRoute

  ApiGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebsocketApi
      StageName: v1
      DeploymentId: !Ref ApiGatewayDeployment
      AccessLogSettings:
        DestinationArn: !GetAtt WebSocketLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","status":"$context.status","responseLength":"$context.responseLength","ip":"$context.identity.sourceIp"}'

Outputs:
  WebsocketApiUrl:
    Description: "Websocket URL"
    Value: !Sub "wss://${WebsocketApi}.execute-api.${AWS::Region}.amazonaws.com/v1"
